export default function FeatureCards() {
  return (
    <div className="feature-cards-wrap">
      <div className="feature-cards" aria-label="Feature cards">
        <div className="feature-card">
          <h4>🗺️ Destination-based planning</h4>
          <p>Pick your destination—we search flights, hotels, and attractions for you.</p>
        </div>
        <div className="feature-card">
          <h4>💰 Budget-aware suggestions</h4>
          <p>Get personalized recommendations that fit your budget and preferences.</p>
        </div>
        <div className="feature-card">
          <h4>📅 Auto-generated itinerary</h4>
          <p>Day-wise schedules, weather, and activity ideas generated by AI.</p>
        </div>
        <div className="feature-card">
          <h4>🤖 AI travel assistant</h4>
          <p>LangChain-powered agent that plans trips from natural language requests.</p>
        </div>
      </div>
    </div>
  );
}

